### ISSUE TITLE
Hi, I seem to have a problem

### ISSUE THREAD

**Issue by qianmianyao** [Ripeey/Conversation-Pyrogram#2]
error:
```python
'Client' object has no attribute 'send_mesage'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/Users/zhoupeng/Downloads/choujiang/main.py", line 28, in start
    await client.send_mesage(message.chat.id, "What's your name?")
AttributeError: 'Client' object has no attribute 'send_mesage'
```

code:
```python
from pyrogram import Client, filters
from convopyro import Conversation
from convopyro import listen_message

plugins = dict(root="plugins")

proxy = {
    "scheme": "http",  # "socks4", "socks5" and "http" are supported
    "hostname": "127.0.0.1",
    "port": 7890,
}

app = Client(
    "",
    bot_token="*****",
    api_hash="ddc6b275***4e6",
    api_id=***,
    in_memory=True,
    proxy=proxy,
    plugins=plugins
)

Conversation(app)


@app.on_message(filters.command('start'))
async def start(client, message):
    await client.send_mesage(message.chat.id, "What's your name?")

    answer = await listen_message(client, message.chat.id, timeout=None)
    await answer.reply(f'hello {answer.text}')


app.run()

```

**Comment by Signko** [comment]
It is `client.send_message()`, not `client.send_mesage()`
